### ISSUE TITLE
Recurring services are not getting synced

### ISSUE THREAD

**Issue by hamza-vd** [OpenSRP/opensrp-client-immunization#163]
Recurring services are not getting synced to the server. This might be due to the location id that was saved in the `recurring_service_records` table is the Location Name and then used to create the event hence the reason why it is failing to sync. Also, the team details are hardcoded. This should not be the case and recurring vaccines should be synced in the same manner like vaccine records are.

**Comment by AnnieMungai** [comment]
@hamza-vd this seems not to be working.

**Comment by hamza-vd** [comment]
@AnnieMungai  - I was unable to reproduce the issue. I found all the service records synced, which were verified after the set vaccine sync time.

**Comment by AnnieMungai** [comment]
@hamza-vd I realized that the servcies are being sycned. However, there was an issue on how this was being displayed on the child profile. See issue #170
