### ISSUE TITLE
Void events under the event_type column on the events table on Unicef Angola

### ISSUE THREAD

**Issue by Janemesi** [opensrp/opensrp-client-immunization#175]
There are some events that are being denoted as void events under the event_type column on the events table as shown in the attached document https://docs.google.com/spreadsheets/d/1bQ5PTky7D-cKZyK_a1Dh-sb8AU2cGudTchTgzJh9hhM/edit?usp=sharing
These void events do not have location ids under the events table however, the void_events table has the location id. 
Based on Kitoto's recommendation [here](https://github.com/onaio/canopy/issues/2132):
Solution:
- Investigate why the new event type that was added in the immunization library is not backward compatible
- Upgrade to the latest immunization library, see if that resolves the issue
- Change the event types on the server from Void Event to Vaccination

**Comment by hilpitome** [comment]
The Void Event was implemented in the immunization library in relation to this [issue](https://github.com/opensrp/opensrp-client-chw/issues/1593). 
It was added in v3.0.2-SNAPSHOT and made backwards compatible in v3.0.4-SNAPSHOT
