### ISSUE TITLE
Update ReadME text

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-immunization#8]

**Comment by ekigamba** [comment]
1. Add descriptions
2. Add screenshots
3. Show flow
4. Update setup + other instructions

**Comment by ekigamba** [comment]
![main - after register single vaccination](https://user-images.githubusercontent.com/31766075/30437995-c75275fc-9978-11e7-8dcf-ab87c4e45f82.png)
![main](https://user-images.githubusercontent.com/31766075/30437996-c754bcea-9978-11e7-8964-8c8a8a3a6f6e.png)
![reg recurring service](https://user-images.githubusercontent.com/31766075/30437999-c759299c-9978-11e7-9d57-80b6e11e0dcf.png)
![register all same-duration vaccinations](https://user-images.githubusercontent.com/31766075/30437998-c754ee2c-9978-11e7-9414-d1e277bcc50f.png)
![register single vaccination](https://user-images.githubusercontent.com/31766075/30438002-c8450a24-9978-11e7-90ee-5f80384076da.png)
![undo - single vaccination](https://user-images.githubusercontent.com/31766075/30437997-c754c15e-9978-11e7-8cc5-7d70ac07e3ec.png)
![vaccination under 5 history page 2](https://user-images.githubusercontent.com/31766075/30438001-c7853f32-9978-11e7-8161-8ef3a5ec1af4.png)
![vaccination under 5 history](https://user-images.githubusercontent.com/31766075/30438000-c784d2a4-9978-11e7-8da9-a2e1a7a26e35.png)

**Comment by ekigamba** [comment]
![rsz_11main_2](https://user-images.githubusercontent.com/31766075/30470553-e5c6e812-99fd-11e7-87be-18b8599918ab.png)

**Comment by ekigamba** [comment]
![10-weeks](https://user-images.githubusercontent.com/31766075/30471708-6a558684-9a02-11e7-95d1-ce48a4532f91.png)
![birth](https://user-images.githubusercontent.com/31766075/30471706-6a5084ae-9a02-11e7-81e3-9761e71929fa.png)
![recorded-service-before-12-hours](https://user-images.githubusercontent.com/31766075/30471707-6a5481a8-9a02-11e7-8710-7fd5a6bfd05b.png)
![recurring-services](https://user-images.githubusercontent.com/31766075/30471709-6a578e34-9a02-11e7-8706-8d147f3bc30f.png)

**Comment by ekigamba** [comment]
![image](https://user-images.githubusercontent.com/31766075/30473412-0e1e0722-9a09-11e7-80ee-614c0dcead04.jpg)
